name: Run unittests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v6
      - name: Run tests script
        run: ./scripts/run_tests.sh
